# 11

In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
home = pd.read_csv("https://bit.ly/3FC52AL")

In [4]:
data = home[['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE','DIS', 'RAD', 'TAX', 'PTRATIO', 'LSTAT']].to_numpy()
target = home['CAT_MEDV'].to_numpy()

In [6]:
train_input, test_input, train_target, test_target = train_test_split(data, target, test_size = 0.3, random_state= 45)

In [7]:
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier

In [9]:
rf = RandomForestClassifier(n_jobs=-1, random_state=45)

In [10]:
scores = cross_validate(rf, train_input, train_target, return_train_score=True, n_jobs=-1)
print(np.round((np.mean(scores['train_score']), np.mean(scores['test_score'])), 2))

[1.   0.95]


In [14]:
rf.fit(train_input, train_target)
print(np.round(rf.feature_importances_, 2))

[0.05 0.04 0.08 0.01 0.03 0.33 0.04 0.05 0.02 0.06 0.07 0.22]


# 12

In [15]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [20]:
print(confusion_matrix(test_target, rf.predict(test_input)))
print(classification_report(test_target, rf.predict(test_input)))

[[121   2]
 [  1  28]]
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       123
           1       0.93      0.97      0.95        29

    accuracy                           0.98       152
   macro avg       0.96      0.97      0.97       152
weighted avg       0.98      0.98      0.98       152



# 13

In [21]:
wine = pd.read_csv("http://bit.ly/wine_csv_data")

In [36]:
wine

alcohol  sugar    pH  class
0         9.4    1.9  3.51    0.0
1         9.8    2.6  3.20    0.0
2         9.8    2.3  3.26    0.0
3         9.8    1.9  3.16    0.0
4         9.4    1.9  3.51    0.0
...       ...    ...   ...    ...
6492     11.2    1.6  3.27    1.0
6493      9.6    8.0  3.15    1.0
6494      9.4    1.2  2.99    1.0
6495     12.8    1.1  3.34    1.0
6496     11.8    0.8  3.26    1.0

[6497 rows x 4 columns]

In [47]:
white = (wine['class'] == 1)

In [48]:
whitewine = wine[white]

In [51]:
whitewine.describe()

alcohol        sugar           pH   class
count  4898.000000  4898.000000  4898.000000  4898.0
mean     10.514267     6.391415     3.188267     1.0
std       1.230621     5.072058     0.151001     0.0
min       8.000000     0.600000     2.720000     1.0
25%       9.500000     1.700000     3.090000     1.0
50%      10.400000     5.200000     3.180000     1.0
75%      11.400000     9.900000     3.280000     1.0
max      14.200000    65.800000     3.820000     1.0

In [50]:
input = whitewine[['alcohol', 'sugar', 'pH']].to_numpy()

In [52]:
from sklearn.preprocessing import StandardScaler

In [53]:
ss = StandardScaler()
ss.fit(input)
scaled = ss.transform(input)

In [54]:
from sklearn.cluster import KMeans

In [56]:
km = KMeans(n_clusters = 4, random_state = 47)
km.fit(scaled)

KMeans(n_clusters=4, random_state=47)

In [57]:
print(np.unique(km.labels_, return_counts=True))

(array([0, 1, 2, 3], dtype=int32), array([1336, 1029, 1125, 1408]))


In [58]:
print(km.transform(scaled[100:101]))

[[2.24640677 3.35782669 3.4108128  0.90739909]]


# 14

In [59]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [60]:
mart = pd.read_csv("https://bit.ly/3RDmQhN")

In [61]:
itemsets = apriori(mart, min_support = 0.15, use_colnames = True)

In [62]:
rules = association_rules(itemsets, metric='confidence', min_threshold= 0.6)

In [63]:
results = rules.sort_values(by=['lift'], ascending = False)

In [64]:
print(np.round(results, 2))

      antecedents    consequents  antecedent support  consequent support  \
6        (potato)      (avocado)                0.17                0.17   
7       (avocado)       (potato)                0.17                0.17   
9   (tuna, olive)         (beef)                0.20                0.31   
11         (beef)  (tuna, olive)                0.31                0.20   
10  (beef, olive)         (tuna)                0.20                0.38   
5    (soda drink)      (cracker)                0.23                0.42   
8    (tuna, beef)        (olive)                0.20                0.44   
1      (baguette)         (tuna)                0.27                0.38   
4       (whiskey)      (cracker)                0.35                0.42   
0          (beef)         (tuna)                0.31                0.38   
3       (whiskey)        (olive)                0.35                0.44   
2          (beef)        (olive)                0.31                0.44   

    support